os: osx
osx_image: xcode11.3
language: swift
script: xcodebuild clean build -workspace Dashborad.xcworkspace -scheme "Dashborad_CI" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=13.3,name=iPhone 8" ONLY_ACTIVE_ARCH=NO CORE_SIGNING_REQUIRED=NO

