os: osx
osx_image: xcode11.3
language: swift

before_install:
- gem install cocoapods
- gem update concurrent-ruby
- pod setup
- pos install
# - pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild clean build -workspace Dashborad.xcworkspace -scheme "Dashborad_CI" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=13.3,name=iPhone 8" ONLY_ACTIVE_ARCH=NO CORE_SIGNING_REQUIRED=NO | xcpretty
- pod lib lint
